### ISSUE TITLE
Setup help needed

### ISSUE THREAD

**Issue by cristimi** [mikakoivisto/controlmyspa-ha-mqtt#2]
I am really interested of your project. I own a spa with Controlmyspa module and I have homeassistant setup working. I feel like I am not experienced enough to setup the docker container that uses the js code by myself.  Would it be possible for you to give a few more details on how to get it up and working ?

**Comment by mikakoivisto** [comment]
I run the docker version of Home assistant so I have everything setup in one docker-compose.yml

This is the part I have for this add on. It could also be totally standalone as long as it can communicate with the mqtt server connected to home assistant.

`  controlmyspa-ha-mqtt:
    container_name: controlmyspa-ha-mqtt
    image: controlmyspa-ha-mqtt
    build:
      context: controlmyspa-ha-mqtt
      dockerfile: Dockerfile
    links:
      - mqtt
    env_file:
      - docker.env`
Since this quite work in progress still you need to build the docker image yourself but that is quite simple. Just run docker-compose up -d --build controlmyspa-ha-mqtt in the directory where you have the docker-compose.yml file. I use environment variables to configure my controlmyspa credentials.

Here's what I have in my docker.env
CONTROLMYSPA_USER=USERNAMEHERE
CONTROLMYSPA_PASS=PASSWORDHERE
CONTROLMYSPA_POLL_INTERVAL=600

**Comment by mikakoivisto** [comment]
Looks like this messes up the indentation but there's a sample docker-compose.yml in the project root directory that has pretty much the same info.

**Comment by cristimi** [comment]
Thanks! I run HASSIO on a NUC and I had already MQTT broker installed. I have filled in credentials for MQTT in docker env file, and deleted the MQTT container from docker-compose.yml file. Homeassistant auto-discovered the MQTT package and now I have a climate entity working in HA.  

For the sake of others that will want to use it so does the config files look like for me:

**docker-compose.yaml**
```
version: '3.3'
services:
  controlmyspa:
    container_name: controlmyspa-mqtt
    image: controlmyspa-mqtt
    build:
      context: ./controlmyspa-mqtt   #path to files from the location of docker-compose.yaml file
    env_file:
      - controlmyspa-mqtt/docker.env
```

**docker.env**
```
CONTROLMYSPA_USER="cmsuser"
CONTROLMYSPA_PASS="cmspass"
CONTROLMYSPA_POLL_INTERVAL=600
MQTTHOST="mqtt server ip adress"
MQTTPORT="1883"
MQTTHASSTOPIC="homeassistant"
MQTTUSER="mqttuser(if any)"
MQTTPASSWORD="mqttpass (if any)"
``` 
Command to run the container:
`docker-compose up -d --build controlmyspa
`
